### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by 22decembre** [reyk/httpd#19] opened 2015-02-14 14:33 UTC
It would be nice to have authentication and controlled access with the most common features :

- bsdauth
- passwd file (classical)
- ldap
- whatever ?

(I believe it's already planned, but I really look forward to see this feature, so I land an issue to follow it.)

Thanks for the great work already done.

**Comment by fobser** [comment] 2015-02-14 16:54
duplicate of #2

**Closed by fobser** 2015-02-14 16:54 UTC

**Comment by reyk** [comment] 2015-02-16 08:35
Only htpasswd file is and will be supported. I add the label "featuritis" to remind us of extra features (eg. ldap) that we reject now but might want to reinspect later.
